-- @where Trigger: WHEN-BUTTON-PRESSED on CTL.COVERAGE2 (form CH32_REST_PACKAGES)
declare
  v_plan   fjson.element_t;
  v_status pls_integer;
begin
  v_status := getplan.access(v_plan, :invoices.plan_id);   -- generated by the designer
  :ctl.plan := fjson.get_string_value(v_plan, 'provider') || ', '
               || fjson.get_string_value(v_plan, 'planName')
               || ' (HTTP ' || v_status || ')';
  :ctl.covered := round(:invoices.total_amount
                        * fjson.get_number_value(v_plan, 'coveragePct') / 100, 2);
  fjson.free_all;
end;
