-- @where Program units GETPLAN (REST Package Spec and Body), generated by the REST Package Designer
--
-- Operation package generated by REST Package Designer 14.1.2.0.0
-- at 2026-09-28 06:49:28+00:00.
-- Originally created from http://localhost:8099/claims-openapi.json
--
-- Do not edit this file using the PL/SQL code editor.
-- Use the REST Package Designer instead.
--
package GETPLAN is
   connect_timeout         pls_integer     := 60000;
   read_timeout            pls_integer     := 60000;
   url_parameters          fjson.element_t := fjson.new_object(2, preserve=>true);
   request_headers         fjson.element_t := fjson.new_object(12, preserve=>true);
   response_headers        fjson.element_t;
   acceptable_status_codes varchar2(32767) := '200';
   parsed_status_codes     varchar2(32767) := '*';

   function access(response out            fjson.element_t,
                   planId                  number          := null)
   return pls_integer;
end;

-- (the same header comment)
package body GETPLAN is
   function access(response out            fjson.element_t,
                   planId                  number          := null)
   return pls_integer is
      http_status     pls_integer;
   begin
      fjson.put_string(url_parameters, 'planId', planId);
      http_status :=
      fhttp.issue_request(
            method             => 'GET',
            server_url_or_id   => 'http://localhost:8098/api/v1',
            uri_template       => '/plans/{planId}',
            url_parameters     => url_parameters,
            request_headers    => request_headers,
            accept             => acceptable_status_codes,
            parse              => parsed_status_codes,
            connect_timeout    => connect_timeout,
            read_timeout       => read_timeout,
            response_headers   => response_headers,
            response_body      => response
      );
      return http_status;
   end;
begin
   fjson.put_string(request_headers, 'accept', 'application/json');
end;
