from formkit import *
f = form('CH31_BEAN', 'CareWell Clinic')
main(f, 'Bookings (Java bean)', 520, 330)
c = block(f, 'CTL')
ch = item(c, 'CHART', None, 12, 10, 496, 150, kind='bean')
ch.setImplementationClass('cw.BarChart')
item(c, 'CHOSEN', 'Appointments of', 100, 170, 150, kind='display', length=40, edge='start')
a = block(f, 'APPOINTMENTS', table='APPOINTMENTS', records=6, where='1 = 2', order='appt_start', scroll=True)
a.setInsertAllowed(False); a.setUpdateAllowed(False); a.setDeleteAllowed(False)
item(a, 'APPT_START', 'Start', 12, 200, 100, dt='datetime', formatMask='DD-MON-YYYY HH24:MI')
item(a, 'STATUS', 'Status', 114, 200, 80, length=10)
item(a, 'REASON', 'Reason', 196, 200, 200, length=100)
trigger(f, 'WHEN-NEW-FORM-INSTANCE', file='ch31/chart-new-form.pls')
trigger(ch, 'WHEN-CUSTOM-ITEM-EVENT', file='ch31/chart-event.pls')
save(f)
