from formkit import *
f = form('CH31_JS', 'CareWell Clinic')
main(f, 'Bookings (JavaScript integration)', 460, 220)
c = block(f, 'CTL')
w = item(c, 'WJSI', None, 440, 4, 8, 8, kind='bean')          # the WJSI bean, out of the way
w.setImplementationClass('oracle.forms.websocketjsi.WebSocketJSI')
s = item(c, 'SEND', 'Send to Page', 12, 10, 100, 20, kind='button')
item(c, 'CHOSEN', 'Appointments of', 200, 12, 150, kind='display', length=40, edge='start')
item(c, 'SESSION', 'Session', 60, 190, 200, kind='display', length=100, edge='start')
a = block(f, 'APPOINTMENTS', table='APPOINTMENTS', records=6, where='1 = 2', order='appt_start', scroll=True)
a.setInsertAllowed(False); a.setUpdateAllowed(False); a.setDeleteAllowed(False)
item(a, 'APPT_START', 'Start', 12, 50, 100, dt='datetime', formatMask='DD-MON-YYYY HH24:MI')
item(a, 'STATUS', 'Status', 114, 50, 80, length=10)
item(a, 'REASON', 'Reason', 196, 50, 200, length=100)
trigger(f, 'WHEN-NEW-FORM-INSTANCE', file='ch31/js-new-form.pls')
trigger(s, 'WHEN-BUTTON-PRESSED', file='ch31/js-send.pls')
trigger(f, 'WHEN-CUSTOM-JAVASCRIPT-EVENT', file='ch31/js-event.pls')
trigger(f, 'WHEN-TIMER-EXPIRED', file='ch31/js-join.pls')
save(f)
