from formkit import *
f = form('CH27_SLOTS', 'CareWell Clinic')
main(f, 'Free Slots', 330, 300)
c = block(f, 'CTL')
item(c, 'DOCTOR_ID', 'Doctor', 50, 10, 44, dt='number', initializeValue='1003', edge='start')
item(c, 'DAY', 'Day', 140, 10, 76, dt='date', formatMask='DD-MON-YYYY', initializeValue='26-OCT-2026', edge='start')
show = item(c, 'SHOW', 'Show', 240, 8, 70, 20, kind='button')
s = block(f, 'SLOTS', table='SLOTS', records=12, scroll=True)
s.setQueryDataSourceType(T.QRDA_TRANS_TRIG_CTID); s.setQueryDataSourceName('')
s.setDMLDataType(T.DMDA_NONE_CTID)             # query only: no ON-INSERT, ON-UPDATE...
s.setInsertAllowed(False); s.setUpdateAllowed(False); s.setDeleteAllowed(False)
item(s, 'SLOT_START', 'Slot', 12, 48, 50, dt='datetime', formatMask='HH24:MI')
item(s, 'BOOKED_FOR', 'Booked for', 64, 48, 240, length=61)
unit(f, 'SLOTS', file='ch27/slots-spec.pls')
unit(f, 'SLOTS', file='ch27/slots-body.pls')
trigger(s, 'ON-SELECT', file='ch27/slots-on-select.pls')
trigger(s, 'ON-FETCH', file='ch27/slots-on-fetch.pls')
trigger(show, 'WHEN-BUTTON-PRESSED', "go_block('SLOTS');\nexecute_query;")
save(f)
