# CW_BILLING: invoices with their lines and payments; a payment updates its invoice's status (Chapter 40)
from formkit import *
f = from_template('/work/forms/cw_template.fmb', 'CW_BILLING', 'Invoices', 560, 330)
f.setMenuModule('cw_app')
c = block(f, 'CTL')
item(c, 'PATIENT_ID', None, dt='number', cnv=None)
item(c, 'SHOWING', None, 12, 8, 400, 18, kind='display', length=100, fontWeight=T.FOWG_BOLD_CTID)
inv = block(f, 'INVOICES', table='INVOICES', records=5, order='invoice_date desc, invoice_id desc', scroll=True)
inv.setInsertAllowed(False); inv.setDeleteAllowed(False)   # updates: per item, so that code may set STATUS
item(inv, 'PATIENT_ID', None, dt='number', cnv=None)
item(inv, 'INVOICE_ID', 'Invoice', 12, 46, 50, dt='number', updateAllowed=False)
item(inv, 'INVOICE_DATE', 'Date', 64, 46, 76, dt='date', formatMask='DD-MON-YYYY', updateAllowed=False)
item(inv, 'PATIENT_NAME', 'Patient', 142, 46, 150, length=61, db=False, updateAllowed=False)
item(inv, 'TOTAL_AMOUNT', 'Total', 294, 46, 60, dt='number', formatMask='99G990D00', updateAllowed=False)
item(inv, 'PAID', 'Paid', 356, 46, 60, dt='number', db=False, formatMask='99G990D00', updateAllowed=False)
item(inv, 'STATUS', 'Status', 418, 46, 60, length=8, updateAllowed=False)
inv.setScrollbarXPosition(480); inv.setScrollbarYPosition(46); inv.setScrollbarLength(82); inv.setScrollbarWidth(10)
ln = block(f, 'INVOICE_LINES', table='INVOICE_LINES', records=4, order='line_no')
ln.setInsertAllowed(False); ln.setUpdateAllowed(False); ln.setDeleteAllowed(False)
item(ln, 'INVOICE_ID', None, dt='number', cnv=None)
item(ln, 'LINE_NO', 'Line', 12, 152, 30, dt='number')
item(ln, 'DESCRIPTION', 'Description', 44, 152, 180, length=60)
item(ln, 'QUANTITY', 'Qty', 226, 152, 30, dt='number')
item(ln, 'UNIT_PRICE', 'Price', 258, 152, 60, dt='number', formatMask='99G990D00')
pay = block(f, 'PAYMENTS', table='PAYMENTS', records=3, order='paid_on, payment_id')
pay.setUpdateAllowed(False); pay.setDeleteAllowed(False)
item(pay, 'PAYMENT_ID', None, dt='number', cnv=None)
item(pay, 'INVOICE_ID', None, dt='number', cnv=None)
item(pay, 'PAID_ON', 'Paid On', 12, 244, 76, dt='date', formatMask='DD-MON-YYYY', initializeValue='$$DATE$$', required=True)
item(pay, 'AMOUNT', 'Amount', 90, 244, 60, dt='number', formatMask='99G990D00', required=True)
m = item(pay, 'METHOD', 'Method', 152, 244, 90, kind='list', length=10, listStyle=T.LSST_POPLIST_CTID,
         initializeValue='CASH')
for i, v in enumerate(['CASH', 'CARD', 'UPI', 'INSURANCE']):
    m.insertElement(i + 1, v.title() if v != 'UPI' else 'UPI', v)
relations(f, inv, [dict(name='INVOICES_LINES', block='INVOICE_LINES', table='INVOICE_LINES', join=[('INVOICE_ID', 'INVOICE_ID')]),
                   dict(name='INVOICES_PAYMENTS', block='PAYMENTS', table='PAYMENTS', join=[('INVOICE_ID', 'INVOICE_ID')])])
trigger(inv, 'POST-QUERY', file='ch40/invoices-post-query.pls')
trigger(pay, 'PRE-INSERT', ':payments.payment_id := payments_seq.nextval;')
trigger(pay, 'POST-INSERT', file='ch40/payments-post-insert.pls')
trigger(f, 'KEY-COMMIT', file='ch40/billing-key-commit.pls')
trigger(f, 'ON-ERROR', 'cw_err.on_error;')
unit(f, 'LOAD_INVOICES', file='ch40/load-invoices.pls')
Trigger.find(f, 'WHEN-NEW-FORM-INSTANCE').setTriggerText("cw_nav.start_form(:parameter.p_user);\nload_invoices;")
trigger(f, 'WHEN-FORM-NAVIGATE', 'load_invoices;')
save(f)
