from formkit import *
f = form('CH22_RUNTIME', 'CareWell Clinic')
main(f, 'Run-Time Properties', 540, 390)
p = block(f, 'PATIENTS', table='PATIENTS', order='last_name, first_name')
item(p, 'MRN', 'MRN', 140, 12, 70, length=10, edge='start', queryOnly=False)
item(p, 'FIRST_NAME', 'First Name', 140, 32, 110, length=30, edge='start')
item(p, 'LAST_NAME', 'Last Name', 140, 52, 110, length=30, edge='start')
g = item(p, 'GENDER', None, 140, 74, 230, 18, kind='radio', length=1, initializeValue='F')
for i, (name, text, value) in enumerate([('FEMALE', 'Female', 'F'), ('MALE', 'Male', 'M'), ('OTHER', 'Other', 'X')]):
    rb = RadioButton(g, name); rb.setLabel(text); rb.setRadioButtonValue(value)
    rb.setXPosition(140 + i * 72); rb.setYPosition(74); rb.setWidth(70); rb.setHeight(16)
label(f, 'GENDER_LBL', 'Gender', 100, 75, 36)
item(p, 'CITY', 'City', 140, 96, 110, length=30, edge='start')
item(p, 'AGE', 'Age', 300, 96, 30, dt='number', kind='display', db=False, edge='start')
c = block(f, 'CTL')
ro = item(c, 'READ_ONLY', 'Read only', 400, 12, 100, kind='check', length=1)
ro.setCheckedValue('Y'); ro.setUncheckedValue('N'); ro.setInitializeValue('N')
a = block(f, 'APP', records=14)
item(a, 'PROPERTY', 'Application property', 12, 136, 150, length=30, insertAllowed=False, updateAllowed=False)
item(a, 'VALUE', 'Value', 164, 136, 360, kind='display', length=200)
unit(f, 'SET_BLOCK_READ_ONLY', file='ch22/set-block-read-only.pls')
trigger(ro, 'WHEN-CHECKBOX-CHANGED', file='ch22/read-only-changed.pls')
trigger(p, 'POST-QUERY', ":patients.age := trunc(months_between(sysdate, :patients.birth_date) / 12);")
item(p, 'BIRTH_DATE', dt='date', cnv=None)
trigger(f, 'WHEN-NEW-FORM-INSTANCE', file='ch22/show-application-properties.pls')
save(f)
