from formkit import *
f = form('CH23_LIBRARY', 'CareWell Clinic')
main(f, 'Patients of Pune', 520, 250)
AttachedLibrary(f, 'cw_lib')
p = block(f, 'PATIENTS', table='PATIENTS', records=8, where="city = 'Pune'", order='last_name, first_name', scroll=True)
item(p, 'MRN', 'MRN', 12, 30, 70, length=10, updateAllowed=False)
item(p, 'FIRST_NAME', 'First Name', 84, 30, 100, length=30)
item(p, 'LAST_NAME', 'Last Name', 186, 30, 100, length=30)
ph = item(p, 'PHONE', 'Phone', 288, 30, 110, length=20)
c = block(f, 'CTL')
e = item(c, 'EDIT', 'Edit', 420, 30, 70, 20, kind='button')
alert(f, 'CW_NOTE', 'CareWell Clinic', 'Message', 'note', ('OK',))
alert(f, 'CW_CAUTION', 'CareWell Clinic', 'Message', 'caution', ('Yes', 'No'))
alert(f, 'CW_STOP', 'CareWell Clinic', 'Message', 'stop', ('OK',))
trigger(f, 'WHEN-NEW-FORM-INSTANCE', file='ch23/when-new-form-instance.pls')
trigger(f, 'KEY-COMMIT', file='ch23/key-commit.pls')
trigger(e, 'WHEN-BUTTON-PRESSED', file='ch23/edit-pressed.pls')
trigger(p, 'KEY-DELREC', file='ch23/key-delrec.pls')
trigger(ph, 'WHEN-VALIDATE-ITEM', file='ch23/phone-validate.pls')
save(f)
