from formkit import *
f = form('CH06_MODULE', 'CareWell Clinic')
f.setValidationUnit(T.VAUN_RECORD_CTID)
f.setInteractionMode(T.INMO_NONBLOCKING_CTID)
f.setMaximumQueryTime(10)
f.setMaximumRecordsFetched(500)
main(f, 'Form Properties', 440, 280)
b = block(f, 'PROPS', records=12)
item(b, 'PROPERTY', 'Property', 16, 30, 150, length=30, insertAllowed=False, updateAllowed=False)
item(b, 'VALUE', 'Value', 168, 30, 250, kind='display', length=80)
c = block(f, 'CONTROL')
btn = item(c, 'CLOSE', 'Close', 346, 240, 72, 20, kind='button')
trigger(btn, 'WHEN-BUTTON-PRESSED', 'exit_form;')
trigger(f, 'WHEN-NEW-FORM-INSTANCE', file='ch06/show-form-properties.pls')
save(f)
