# CH34_PERF: fetches all appointments and measures the session's work. ARRAY (environment) builds a
# variant with that Query Array Size, CH34_PERF_A<n>; without it, the block's default (records displayed).
from formkit import *
import os
n = os.environ.get('ARRAY')
f = form('CH34_PERF' + ('_A' + n if n else ''), 'CareWell Clinic')
main(f, 'Fetching Appointments', 520, 300)
c = block(f, 'CTL')
bn = item(c, 'NONE', 'No Lookups', 12, 8, 90, 20, kind='button')
bq = item(c, 'QUERIES', 'Three Queries', 108, 8, 90, 20, kind='button')
bp = item(c, 'CALL', 'One Call', 204, 8, 90, 20, kind='button')
item(c, 'ARRAY', 'Array size', 360, 10, 40, kind='display', dt='number', edge='start', initializeValue=n or '10')
item(c, 'MODE', None, 12, 34, 110, kind='display', length=20)
item(c, 'ROWS', 'Rows', 160, 34, 50, kind='display', dt='number', edge='start')
item(c, 'CS', 'Centiseconds', 290, 34, 50, kind='display', dt='number', edge='start')
item(c, 'TRIPS', 'Round trips', 160, 54, 50, kind='display', dt='number', edge='start')
item(c, 'EXECS', 'Executions', 290, 54, 50, kind='display', dt='number', edge='start')
a = block(f, 'APPTS', table='APPOINTMENTS', records=10, order='appt_id', scroll=True)
if n: a.setRecordsFetchedCount(int(n))
a.setInsertAllowed(False); a.setUpdateAllowed(False); a.setDeleteAllowed(False)
item(a, 'APPT_ID', 'Appt', 12, 88, 40, dt='number')
item(a, 'APPT_START', 'Start', 54, 88, 90, dt='datetime', formatMask='DD-MON-YY HH24:MI')
item(a, 'PATIENT', 'Patient', 146, 88, 130, kind='display', length=61, db=False)
item(a, 'DOCTOR', 'Doctor', 278, 88, 110, kind='display', length=40, db=False)
item(a, 'BILLED', 'Billed', 390, 88, 60, kind='display', dt='number', db=False)
for col in ['PATIENT_ID', 'DOCTOR_ID']:
    item(a, col, dt='number', cnv=None)
unit(f, 'SESSION_STAT', file='ch34/session-stat.pls')
unit(f, 'MEASURE', file='ch34/measure.pls')
trigger(a, 'POST-QUERY', file='ch34/post-query.pls')
trigger(bn, 'WHEN-BUTTON-PRESSED', "measure('N', 'No lookups');")
trigger(bq, 'WHEN-BUTTON-PRESSED', "measure('Q', 'Three queries');")
trigger(bp, 'WHEN-BUTTON-PRESSED', "measure('P', 'One call');")
save(f)
