from formkit import *
f = form('CH03_PATIENTS', 'Patients')
main(f, 'Patients', 520, 250)
b = block(f, 'PATIENTS', table='PATIENTS', order='last_name, first_name')
item(b, 'MRN', 'MRN', 16, 30, 80, length=10)
item(b, 'FIRST_NAME', 'First Name', 104, 30, 130, length=30)
item(b, 'LAST_NAME', 'Last Name', 242, 30, 130, length=30)
item(b, 'BIRTH_DATE', 'Birth Date', 16, 76, 80, dt='date')
item(b, 'AGE', 'Age', 104, 76, 40, dt='number', kind='display', db=False)
item(b, 'GENDER', 'Gender', 152, 76, 50, length=1)
item(b, 'BLOOD_GROUP', 'Blood Group', 210, 76, 60, length=3)
item(b, 'PLAN_ID', 'Plan', 278, 76, 50, dt='number', lovName='LOV_PLANS')
item(b, 'CITY', 'City', 16, 122, 130, length=30)
item(b, 'PHONE', 'Phone', 154, 122, 130, length=20)
lov(f, 'LOV_PLANS', 'select plan_id, provider || \' - \' || plan_name as plan from insurance_plans order by 1',
    [('PLAN_ID', 'Id', 30, 'PATIENTS.PLAN_ID'), ('PLAN', 'Plan', 200, None)], title='Insurance Plans')
unit(f, 'AGE_IN_YEARS', file='ch03/age-in-years.pls')
trigger(b, 'POST-QUERY', file='ch03/patients-post-query.pls')
trigger(Item.find(b, 'BIRTH_DATE'), 'WHEN-VALIDATE-ITEM', file='ch03/birth-date-validate.pls')
trigger(f, 'WHEN-NEW-FORM-INSTANCE', 'execute_query;')
save(f)
