from formkit import *
f = form('CH20_SEARCH', 'CareWell Clinic')
main(f, 'Find Patients', 580, 300)
p = block(f, 'PATIENTS', table='PATIENTS', records=8, order='last_name, first_name', scroll=True)
item(p, 'MRN', 'MRN', 12, 24, 62, length=10)
item(p, 'FIRST_NAME', 'First Name', 76, 24, 78, length=30, caseInsensitiveQuery=True)
item(p, 'LAST_NAME', 'Last Name', 156, 24, 82, length=30, caseInsensitiveQuery=True)
item(p, 'GENDER', 'G', 240, 24, 18, length=1, caseRestriction=T.CARS_UPPER_CTID)
item(p, 'BIRTH_DATE', 'Born', 260, 24, 70, dt='date', formatMask='DD-MON-YYYY', queryLength=60)
item(p, 'BLOOD_GROUP', 'Blood', 332, 24, 34, length=3)
item(p, 'CITY', 'City', 368, 24, 76, length=30, caseInsensitiveQuery=True)
item(p, 'PLAN_ID', 'Plan', 446, 24, 30, dt='number', queryLength=40)
item(p, 'PHONE', 'Phone', 478, 24, 86, length=20)
p.setScrollbarXPosition(566); p.setScrollbarYPosition(24); p.setScrollbarLength(128); p.setScrollbarWidth(10)
c = block(f, 'CTL')
item(c, 'AGE', 'Age', 60, 170, 30, dt='number', edge='start',
     hint='An age in years: the patients who are that old today')
item(c, 'HITS', 'Rows fetched', 190, 170, 40, kind='display', length=10, edge='start')
item(c, 'LAST_QUERY', 'Last query', 12, 204, 552, 60, length=2000, multiLine=True,
     insertAllowed=False, updateAllowed=False, keyboardNavigable=False)
trigger(p, 'PRE-QUERY', file='ch20/patients-pre-query.pls')
trigger(p, 'KEY-EXEQRY', file='ch20/key-exeqry.pls')
trigger(f, 'WHEN-NEW-FORM-INSTANCE', "go_block('PATIENTS');")
save(f)
