# CH39_DOCTORS: deleting a doctor only marks the row inactive (Chapter 39, recipe 9)
from formkit import *
f = form('CH39_DOCTORS', 'CareWell Clinic')
main(f, 'Doctors', 560, 260)
c = block(f, 'CTL')
si = item(c, 'SHOW_INACTIVE', 'Show inactive doctors', 12, 8, 160, kind='check', length=1)
si.setCheckedValue('Y'); si.setUncheckedValue('N'); si.setInitializeValue('N')
trigger(si, 'WHEN-CHECKBOX-CHANGED', file='ch39/show-inactive.pls')
b = item(c, 'REACTIVATE', 'Reactivate', 200, 6, 90, 22, kind='button', mouseNavigate=False, keyboardNavigable=False)
trigger(b, 'WHEN-BUTTON-PRESSED', file='ch39/reactivate.pls')
d = block(f, 'DOCTORS', table='DOCTORS', records=10, where="active = 'Y'", order='last_name, first_name', scroll=True)
item(d, 'DOCTOR_ID', 'ID', 12, 50, 40, dt='number', updateAllowed=False)
item(d, 'FIRST_NAME', 'First Name', 54, 50, 90, length=30)
item(d, 'LAST_NAME', 'Last Name', 146, 50, 90, length=30)
item(d, 'SPECIALTY', 'Specialty', 238, 50, 150, length=40)
item(d, 'CONSULT_FEE', 'Fee', 390, 50, 50, dt='number')
ac = item(d, 'ACTIVE', 'Active', 450, 50, 40, kind='check', length=1)
ac.setCheckedValue('Y'); ac.setUncheckedValue('N'); ac.setLabel('')
d.setScrollbarXPosition(500); d.setScrollbarYPosition(50); d.setScrollbarLength(160); d.setScrollbarWidth(10)
trigger(d, 'ON-DELETE', file='ch39/doctors-on-delete.pls')
trigger(f, 'WHEN-NEW-FORM-INSTANCE', "go_block('DOCTORS');\nexecute_query;")
save(f)
